apiVersion: 1

contactPoints:
  - orgId: 1
    name: aircare-default
    receivers:
      - uid: aircare-default-receiver
        type: webhook
        settings:
          url: http://nodered:1880/alert
          httpMethod: POST
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: aircare-default
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
